default: &default
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: identity_development

test:
  <<: *default
  database: identity_test

production:
  <<: *default
